spring:
  application:
    name: DYNA-core-adapter
  main:
    web-application-type: none
  config:
    import: "classpath:dynamisk-adapter.yaml"

fint:
  adapter:
    id: fint-core-dyna
    orgId: fintlabs-no
    baseUrl: https://beta.felleskomponent.no
    idpUri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    heartbeat-interval: 20

